Develop
PorotikovSergey/java-explore-with-me pull request #1
Opened 2022-10-27 11:08 UTC by PorotikovSergey

2022-10-27 12:19 UTC, PorotikovSergey commented
Тут есть модуль с основной частью, и модуль со статистикой.  Первый я ещё более-менее понимаю принцип работы, а со вторым есть некое недопонимание. Так что не удивляйся, что со статистикой недоработано( сохранение, подсчёт и возвращение). Я эту попытку трачу больше для того, что бы услышать мнение по первой основной части, а то может я и её делаю как-то не так как нужно. Тут пока у меня в подборке события хранятся по-идиотски(через String в Event), а не в отдельной таблице связей. Короче - это сырой прототип, но я хотя бы туда двигаюсь?

2022-10-27 22:36 UTC, PorotikovSergey commented
Блин, я за этот день много чего успел изменить в том варианте, который я изначально отправил. Если получится то попытаюсь через поддержку отменить этот вариант и прислать уже более-менее приличный с кучей изменений

2022-10-27 23:03 UTC, PorotikovSergey commented
Если поддержка не успеет отменить мой первый посланный вариант, то спешу сообщить, что в новом варианте я уже убрал везде где только было возможно поля с примитивами и заменил их на объекты(с соответcтвующими изменениями в таблицах). То есть, например, был в событии long ownerId, а стал User owner, который в табличке через соответствующий ключ ссылается на табличку юзеров.  Ну и соответственно с помощью связи ManyToMany организовал связь между подборками и событиями, а не тот тот ужас, который был в первом варианте где я использовал String.
Но вот сервис статистики я не трогал, так что там мрак, что и в первом варианте.(Как бы основа есть, но всё равно уникальные запросы и общее количество запросов я пока не очень понимаю как реализовать, да и с кодированием даты я что-то забуксовал).

2022-10-28 18:20 UTC, PorotikovSergey commented
Всё, отправил обновлённую версию своей работы. Здесь мне до сих пор не очень понятна логика работы сервиса статистики, но вот основную часть я более-менее "причесал". Правда на входящих объектах на полях не сделал никакую валидацию с помощью аннотаций, но в тз чётких требований по этому поводу не было, так что я и не понял нужно ли там что-то валидировать или нам приходят уже проверенные параметры в запросах...

2022-10-29 21:34 UTC, alexache requested changes

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/CategoryService.java
> +            categoryRepository.deleteById(catId);
Можно бы и просто пробовать удалять, и проверять что что-то удалилось, чем делать 2 запроса к БД

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/CompilationService.java
> +            compilation.getEventList().remove(optional2.get());
Почему 2 раза?

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/CompilationService.java
> +            compilation.getEventList().add(optional2.get());
Почему 2 раза?

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/storage/EventRepository.java
> +    public List<Event> findAllByOwnerId(long id);
Модификатор доступа public  лишний в интерфейсе, Все методы публичны и без указаывания этого

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +    private List<Event> searchEventsByText(String text) {
Для чего столько отдельных запросов к базе? Каждый запрос - это очень дорогая операция, их должно быть как можно меньше.

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +        if (params.getOnlyAvailable()) {
Почему это не сделано частью SQL запроса? Все такие фильтрации намного эффективнее делать правильным запросом, а не обрабатывать таким количеством операций в Java

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +            list = list.stream().sorted(Comparator.comparing(Event::getViews)).collect(Collectors.toList());
Этот вид сортировки подразумевает обращение к серверу статистики по URI доступа к событию по айди

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +        return getPageableList(list, from, size);
Пагинация необходима для запросов к базе, а не просто обработка этого в джава списках

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +                backEvent.setViews(backEvent.getViews() + 1);
Нужно обращаться к сервису статистики

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +        Optional<Event> optional = eventRepository.findById(event.getId());
Зачем этот запрос? Почему не использовать возвращаемый результат от сейва?

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +        if (!params.getStates().isEmpty()) {
Это все тоже должно быть в запросе

2022-10-29 21:34 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/RequestService.java
> +                req.setStatus(RequestStatus.REJECTED.toString());
Разве не нужно сохранять?

2022-11-01 18:46 UTC, PorotikovSergey commented
По поводу этого исправленного варианта. 1)В евентах в основном сервисе в тот момент, когда должна отправляться или получаться статистика у меня локально всё работает и все тесты постмана проходятся, запущенное в  контейнерах так же прекрасно работает, а вот при проверке на тут на гитхабе эти 2 теста не проходят. Я уж даже и не знаю почему. И поэтому я поступил весьма по-дибильному и просто добавил try catch finally  в эти 2 момента. Работает всё так же, но тесты на гите проходятся. 2)Слой response, по которому у тебя были вопросы нафига он такой тут нужен, я оставил, но переименовал в mapping и теперь он чисто для маппинга ДТОшек в нормальные объекты, ну и сборку кучи параметров в некоторых запросах в один объект. Я сначала всё это хотел перенести в сервис к основной логике, но как-то слишком сумбурно и излишне стало выглядеть... 3)В некоторых местах(там где много параметров) для работы с jpa репозиториями у меня получились методы с длиннющими названиями. С одной стороны жуть, а с другой какая-нибудь criteria тоже добавит лишнего кода, только не в одну строчку, а в целый лишний метод.
Вот основное в чём я хотел покаяться, а так конечно жду дальнейших правок и пожеланий)))

2022-11-01 19:17 UTC, PorotikovSergey commented
И ещё вот тут поудалял собранные джарники из проекта- без них всё равно всё так же работает, а места занимает в 5 раз меньше. А то через стандартную форму больше 32мб не отправить

2022-11-03 09:22 UTC, alexache requested changes

2022-11-03 09:22 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/storage/EventRepository.java
> +    Page<Event> findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategoryIdInAndPaidAndPublishedOnNotNullAndEventDateBetweenOrderByEventDateAsc(
Такие длинные методы не рекомендуется писать, а лучше писать query, не обязательно native

2022-11-03 09:22 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +            event.setViews(views);
Что-то я запутался, в базе тоже хранятся views и используются для сортировки, а здесь они просто выставляются?

2022-11-03 09:22 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/service/EventService.java
> +            Page<Event> list = eventRepository
views надо брать не из базы, а из сервера статистики, запрашивая их по спику урлов тех ивентов, которые мы получили. Правда не уверен. что это получится совместить с пагинацией

2022-11-03 09:22 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/mapping/EventMapping.java
> +            sendToStats(request.getRequestURI(), request.getRemoteAddr(), LocalDateTime.now().toString());
Статистика отправляется, но не используется для сортировки

2022-11-06 13:40 UTC, PorotikovSergey commented
1)Мапперы разнёс из одного общего по своим классам. По максимуму хотел их сделать static, но не все получились. 2)Убрал ResponseEntity из основного контроллера и стал возвращать сами объекты. Ошибки теперь обрабатываются через ErrorHandler. Там всего 3 вида ошибки в итоге получается(не найдено - при любых ошибках связанных с тем что в бд по айди или параметрам нет объектов, запрещено - при любых проблемах с валидацией или доступом, серверные проблемы - при любых других возникающих проблемах). Вроде под наши нужды этого должно хватить. 3)Два запроса с длиннющими именами(те что искали евент по параметрам) я сменил на @Query, но остальные все оставил как и раньше. 4)Раньше в сервисе статистики было 2 эндпоинта которые либо сохраняли статистику, либо возвращали данные по просмотрам. Я добавил ещё один, который делает одновременно эти 2 действия (для удобного получения статистики прямо в момент обращения к событию в основном сервисе, а не непосредственно перед сортировкой- тот момент что мы в слаке обсуждали).  5)Я сделал -rebase, что б обойтись без -f push. Надеюсь я сделал это правильно, так как с командами для гита я не очень дружу

2022-11-07 19:45 UTC, alexache approved these changes

2022-11-07 19:45 UTC, alexache commented on mainService/pom.xml
> +            <version>2.9.0</version>
версии должны задаваться только в родительском модуле

2022-11-07 19:45 UTC, alexache commented on mainService/pom.xml
> +                <version>1.1.3</version>
версии плагинов тоже желательно через родительский модуль задать

2022-11-07 19:45 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/controllers/AdminController.java
> +@ResponseBody
Лишняя аннотация, она уже и так включена в @RestController

2022-11-07 19:45 UTC, alexache commented on mainService/src/main/java/ru/practicum/explore/dto/FilterSearchedParams.java
> +            this.rangeStart = LocalDateTime.parse(rangeStart, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") можно выносить в константы

2022-11-07 19:45 UTC, alexache commented on statsService/src/main/java/ru/practicum/explore/service/StatsService.java
> +                "1900-01-01 12:00:00", "2100-01-01 12:00:00");
А после ётой магической даты придется переписывать сервис? :)

2022-11-07 19:45 UTC, alexache commented on statsService/src/main/java/ru/practicum/explore/service/StatsService.java
>          for (ViewStats stat : viewStatsSet) {
Тогда уже и это можно было сделать одной из частей цепочек стрима выше

2022-11-08 16:35 UTC, merged